name: Deploy Agent

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_agent:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - name: Restart App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AGENTS_SERVER_SSH_HOST }}
          username: ${{ secrets.AGENTS_SERVER_SSH_USER }}
          key: ${{ secrets.AGENTS_SERVER_SSH_KEY }}
          script: |
            cd /var/www/agents/weather-agent
            git pull origin main
            uv pip install -r requirements.txt
            stl restart weather_agent
